slam_toolbox:
  ros__parameters:
    # TF Frames
    odom_frame: odom
    map_frame: map
    base_frame: base_link  # <--- This is the crucial change for your setup
    scan_topic: /scan

    # SLAM Settings (Optimized for playback)
    mode: mapping # mapping or localization
    map_update_interval: 1.0
    max_laser_range: 20.0 # MIT dataset has long corridors
    resolution: 0.05

    # Processor
    transform_publish_period: 0.05 # 20Hz
    map_start_pose: [0.0, 0.0, 0.0]