locations:
  mailroom:
    x: 0.0
    y: 0.0
    w: 1.0
  office_101:
    x: 2.5
    y: 1.0
    w: 1.0
  office_102:
    x: 5.0
    y: -1.5
    w: 1.0
  lobby:
    x: 1.0
    y: 3.0
    w: 1.0